language: java
install: true
sudo: true

notifications:
  email:
    recipients:
    - michal.nawrot.mn.mn@gmail.com
    on_success: always
    on_failure: always

cache:
  directories:
  - .autoconf
  - $HOME/.m2


script:
- mvn clean install -U
- mvn validate
stages:
- compile
- test
- name: deploy
  if: branch = release

before_deploy:
- git config --local user.name "bigoz005"
- git config --local user.email "209405@edu.p.lodz.pl"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: $TOKEN
  file: /home/travis/build/IIS-ZPI/ZPI_2019_Dzienni_IO2_3/target/ZPI_2019_Dzienni_IO2_3-1.0-SNAPSHOT.jar
  skip_cleanup: true
  on:
    branch: release
