language: java

before_install:
- chmod +x mvnw

install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

notifications:
  email:
    recipients:
    - michal.nawrot.mn.mn@gmail.com
    on_success: never
    on_failure: always

script:
- mvn validate
- mvn compile
- mvn test -B
- if [ "$TRAVIS_BRANCH" == "test" ]; then
  mvn package;
  fi


before_deploy:
- git config --local user.name "Travis CI"
- git config --local user.email "travis@noreply.github.com"
- export GIT_TAG=$TRAVIS_BRANCH-v$MAJOR_VERSION.$MINOR_VERSION.$TRAVIS_BUILD_NUMBER
- git tag -a $GIT_TAG -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"

deploy:
  provider: releases
  api_key: $TOKEN
  tag_name: $TRAVIS_TAG
  target_commitish: $TRAVIS_COMMIT
  name: $TRAVIS_TAG
  overwrite: true
  file: "src/main/java/com.zpi/NbpCommunication.java"
  skip_cleanup: true
  on:
    repo: IIS-ZPI/ZPI_2019_Dzienni_IO2_3
    tags: true
    all_branches: true
    branches:
      only:
      - travis_releasy_feature
    body: "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"